data.probes.path=src/main/resources/probes.txt
data.fingerprints.path=src/main/resources/fingerprints
data.messages.path=src/main/resources/messages
data.cve.database.path=src/main/resources/cves.sqlite

output.dir=output

network.socket.timeout=1000
network.socket.interval=2000

tls.cipher_suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 TLS_RSA_WITH_AES_128_CBC_SHA TLS_RSA_WITH_3DES_EDE_CBC_SHA TLS_DHE_RSA_WITH_AES_128_CBC_SHA TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA TLS_DHE_RSA_WITH_AES_256_CBC_SHA
tls.version=TLS12
tls.compression_method=NULL

# The similarity threshold for matching candidates (0.0 means all matches are accepted, 1.0 means only perfect matches are accepted)
fingerprint.similarity.threshold=0.9


